import Search from '@/components/search'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="mx-auto flex max-w-screen-lg items-center justify-center gap-4 p-4">
          <Link href="/" className="transition-opacity">
            <Image
              src="/solana_icon.png"
              alt="Solana Logo"
              width={40}
              height={40}
              priority
            />
          </Link>
          <Search className="" />
        </div>
        {children}
      </body>
    </html>
  )
}
